/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api579calculator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Pipe testPipe = new Pipe(100.0, 10, Pipe.PipeType.STRAIGHT, 2.1287, 147.0, 1.0, 1.0, 0.4, 1.0);
        testPipe.printPipeInfo();
    }
}
