/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api579calculator;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    static final String APPLICATION_WINDOW_TITLE = "API 579-1 Straight Pipe FFS Calculator";
    static final double WINDOW_WIDTH = 800.0;
    static final double WINDOW_HEIGHT = 600.0;

    // @TODO install java 11 and then get application running on java 11
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("mainView.fxml"));
        primaryStage.setTitle(APPLICATION_WINDOW_TITLE);
        Scene scene = new Scene(root, WINDOW_WIDTH, WINDOW_HEIGHT);

        // used for RichTextFX codeArea text highlighting
        scene.getStylesheets().add(getClass().getResource("mainView.css").toExternalForm());

        primaryStage.setScene(scene);
        primaryStage.show();
    }

}
