/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.abundantsalmon.api579calculator;

import com.abundantsalmon.api579calculator.ui.UiFX;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(UiFX.class, args);
    }
}

